cache: apt
sudo: false
language: python
python:
  - "3.5"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libhdf5-serial-dev
    - libstdc++6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy libgcc
  - pip install pytest-pep8
  - pip install -r requirements.txt
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl
  - python -m spacy.en.download all > spacy.log
install:
  - python setup.py install
before_script:
  - mkdir pickle word_vectors
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/w2v.tgz | tar xz -C word_vectors
  - python scripts/split_corpus.py pickle -t 4282 -d 454 -l
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse
  - TEST_SUITE=dense
  - TEST_SUITE=nn
  - TEST_SUITE=tune
  - TEST_SUITE=convert
script:
  - ci/test.sh
