cache: apt
sudo: false
dist: trusty
language: python
python:
  - "3.5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libstdc++6
    - gcc-4.8
    - g++-4.8
    - cmake
    - mercurial
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-serialization1.55-dev
    - libboost-test1.55-dev
    - libboost-regex1.55-dev
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy libgcc
  - pip install pytest-pep8
  - pip install -r requirements.txt
  - python -m nltk.downloader averaged_perceptron_tagger punkt
  - ci/install-dynet.sh
  - export LD_LIBRARY_PATH="$HOME/dynet:$LD_LIBRARY_PATH"
  - wget http://nlp.stanford.edu/software/stanford-postagger-2015-12-09.zip
  - unzip stanford-postagger-2015-12-09.zip
  - jdk_switcher use oraclejdk8
  - export CLASSPATH="$PWD/stanford-postagger-2015-12-09"
  - export STANFORD_MODELS="$PWD/stanford-postagger-2015-12-09/models"
install:
  - python setup.py install
before_script:
  - mkdir pickle word_vectors
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/w2v.tgz | tar xz -C word_vectors
  - python scripts/split_corpus.py -l pickle
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse
  - TEST_SUITE=dense
  - TEST_SUITE=mlp
  - TEST_SUITE=bilstm
  - TEST_SUITE=tune
  - TEST_SUITE=convert
script:
  - travis_wait 120 ci/test.sh
