sudo: false
language: python
python:
  - "3.5"
before_install:
  - pip install pytest-pep8
  - pip install -r requirements.txt
  - python -m spacy.en.download all > spacy.log
install:
  - python setup.py install
before_script:
  - mkdir pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
env:
  - TEST_SUITE=unit
  - TEST_SUITE=convert
script:
  - ci/test.sh
