language: python
python:
  - "3.3"
sudo: false
# command to install dependencies
install: pip install -r requirements.txt
# command to prepare for tests
before_script:
  - curl -O http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz
  - mkdir pickle
  - tar xvzf ucca_corpus_pickle.tgz -C pickle
  - python setup.py
# command to run tests
script: python parser/parser.py pickle -b
